<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:pd="http://xmlns.tibco.com/bw/process/2003" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pfx="http://www.tibco.com/CLEver/Exception" xmlns:pfx2="http://www.tibco.com/CLEver/InternalException">
    <xsd:import namespace="http://www.tibco.com/CLEver/InternalException" schemaLocation="/Shared Resources/Schema Definitions/CLEver/Error.xsd"/>
    <pd:name>Processes/InternalServices/Exception Handler/FormatErrorHumanReadable.process</pd:name>
    <pd:startName>Start</pd:startName>
    <pd:startType>
        <xsd:element name="Input">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element ref="pfx2:Exception"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
    </pd:startType>
    <pd:startX>150</pd:startX>
    <pd:startY>64</pd:startY>
    <pd:returnBindings>
        <Output>
            <ErrorMessage>
                <xsl:value-of select="if (contains($Start/Input/pfx2:Exception/pfx2:Error/pfx2:ErrorReport/Msg, 'ORA-00001')) then&#xA;'Object with the same name already exists'&#xA;else&#xA;$Start/Input/pfx2:Exception/pfx2:Error/pfx2:ErrorReport/Msg"/>
            </ErrorMessage>
        </Output>
    </pd:returnBindings>
    <pd:endName>End</pd:endName>
    <pd:endType>
        <xsd:element name="Output">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="ErrorMessage" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
    </pd:endType>
    <pd:endX>450</pd:endX>
    <pd:endY>65</pd:endY>
    <pd:errorSchemas/>
    <pd:processVariables/>
    <pd:transition>
        <pd:from>Start</pd:from>
        <pd:to>End</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
</pd:ProcessDefinition>